// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiX5K8Xf9zmjCsCuE2VsL1hPZBTyH4wVQ',
    appId: '1:1030058723818:web:f0610e2740cdbc45204a93',
    messagingSenderId: '1030058723818',
    projectId: 'flutter-app-1fe84',
    authDomain: 'flutter-app-1fe84.firebaseapp.com',
    storageBucket: 'flutter-app-1fe84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCizIsGDDq8YiDIjPK1OHdV-yKx0jzD0D8',
    appId: '1:1030058723818:android:80d0a43ed37e8954204a93',
    messagingSenderId: '1030058723818',
    projectId: 'flutter-app-1fe84',
    storageBucket: 'flutter-app-1fe84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWfw1ZJ8DQVYRrJbO8ZGn6yLzrmzDfAmI',
    appId: '1:1030058723818:ios:0e3e3f5166a02e95204a93',
    messagingSenderId: '1030058723818',
    projectId: 'flutter-app-1fe84',
    storageBucket: 'flutter-app-1fe84.appspot.com',
    iosClientId: '1030058723818-hua1nqk7bra29r42lee6r5t4eagj3db4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWfw1ZJ8DQVYRrJbO8ZGn6yLzrmzDfAmI',
    appId: '1:1030058723818:ios:0e3e3f5166a02e95204a93',
    messagingSenderId: '1030058723818',
    projectId: 'flutter-app-1fe84',
    storageBucket: 'flutter-app-1fe84.appspot.com',
    iosClientId: '1030058723818-hua1nqk7bra29r42lee6r5t4eagj3db4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppFirebase',
  );
}
